---
format_version: 10
pipelines:
    java_microservice:
        group: microservices
        lock_behavior: unlockWhenFinished
        label_template:
        materials: 
            git_java_microservice:
                git: https://github.com/mtararujs/api_tests_ci.git
                branch: main
                shallow_clone: true
                auto_update: true
        stages: 
            - build:
                jobs:
                    build:
                    tasks:
                        - exec:
                            command: bash
                            arguments:
                                - -c
                                - echo "Building java app"
            - deploy-dev:
                jobs:
                    build:
                    tasks:
                        - exec:
                            command: bash
                            arguments:
                                - -c
                                - echo "Deploy in dev"
            - test-dev:
                jobs:
                    build:
                    tasks:
                        - exec:
                            command: bash
                            arguments:
                                - -c
                                - echo "Test on dev"
            - deploy-int:
                jobs:
                    build:
                    tasks:
                        - exec:
                            command: bash
                            arguments:
                                - -c
                                - echo "Deploy in int"
            - test-int:
                jobs:
                    build:
                    tasks:
                        - exec:
                            command: bash
                            arguments:
                                - -c
                                - echo "Test on int"
            - deploy-dev:
                jobs:
                    build:
                    tasks:
                        - exec:
                            command: bash
                            arguments:
                                - -c
                                - echo "Deploy in prd"
            - test-dev:
                jobs:
                    build:
                    tasks:
                        - exec:
                            command: bash
                            arguments:
                                - -c
                                - echo "Test on prd"
            